###
POST https://localhost:5001/api/administrator/
Content-Type: application/json

{
    "Name": "Lorem Ipsum",
    "Password": "123456"
}
###

###
GET https://localhost:5001/api/administrator/
###

###
GET https://localhost:5001/api/administrator/1
###

###
PUT https://localhost:5001/api/administrator/
Content-Type: application/json

{
    "Id": 1,
    "Name": "Ipsum Lorem",
    "Password": "12345"
}


###
DELETE  https://localhost:5001/api/administrator/1
###