###
POST https://localhost:5001/api/student-vacancy/
Content-Type: application/json

{
    "StudentId": 1,
    "Name": "Lorem ipsum",
    "VacancyId": 1
}
###

###
PUT https://localhost:5001/api/student-vacancy/
Content-Type: application/json

{
    "Id": 1,
    "StudentId": 2,
    "VacancyId": 2
}
###

###
DELETE  https://localhost:5001/api/student-vacancy/1
###